name: commit-check
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


jobs:
  conventional-commits:
    if: ${{ !startsWith(github.head_ref, 'renovate/') }}
    runs-on: ubuntu-latest
    # SECURITY: # https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
    permissions: read-all
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6
        with:
          python-version: "3.14"

      - name: commitizen check
        run: |
          pip install commitizen
          cz check --rev-range ${{ github.event.pull_request.base.sha }}..HEAD

  dco:
    if: ${{ !startsWith(github.head_ref, 'renovate/') }}
    runs-on: ubuntu-latest
    # SECURITY: # https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
    permissions: read-all
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6
        with:
          python-version: '3.14'

      - name: dco check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DCO_CHECK_EXCLUDE_PATTERN: (dependabot|github-actions)\[bot\]@users\.noreply\.github\.com
          DCO_CHECK_VERBOSE: '1'
        run: |
          pip install -U dco-check
          dco-check
